config/routes.rb
DanceApp::Application.routes.draw do
  resources :subjects

  resources :student_groups

  resources :student_classes
  resources :class_students

  resources :teachers

  resources :lounges
  resources :teachers  
  resources :centers
  resources :users
  resources :sessions
  resources :students
  root  :to => 'sessions#new'
  match '/mainMenu', :to => 'pages#mainMenu'
  match '/userAdd', :to => 'users#new'
  match '/userClear', :to => 'users#clearUser' 
  match '/studentClear', :to => 'students#clearStudent'   
  match '/teacherClear', :to => 'teachers#clearTeacher'     
  match '/teacherAfterSubmit', :to => 'teachers#afterSubmit'       
  match '/centerClear', :to => 'centers#clear_center'     
  match '/subjectClear', :to => 'subjects#clear_subject'
  match '/loungeClear', :to => 'lounges#clear_lounge'       
  match '/StudentClassClear', :to => 'student_classes#clear_student_class'  
  match '/signout', :to => 'sessions#destroy'

end

app/models/student_group.rb
# -*- encoding : utf-8 -*-
class StudentGroup < ActiveRecord::Base
  #has_many :student_classes
  #has_many :students
  has_many :st_classes
  has_many :st  
end

app/controllers/student_groups_controller.rb
# -*- encoding : utf-8 -*-
class StudentGroupsController < ApplicationController
  # GET /student_groups
  # GET /student_groups.xml
  def index
    @student_groups = StudentGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @student_groups }
    end
  end

  # GET /student_groups/1
  # GET /student_groups/1.xml
  def show
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student_group }
    end
  end

  # GET /student_groups/new
  # GET /student_groups/new.xml
  def new
    @student_group = StudentGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student_group }
    end
  end

  # GET /student_groups/1/edit
  def edit
    @student_group = StudentGroup.find(params[:id])
  end

  # POST /student_groups
  # POST /student_groups.xml
  def create
    @student_group = StudentGroup.new(params[:student_group])

    respond_to do |format|
      if @student_group.save
        format.html { redirect_to(@student_group, :notice => 'Student group was successfully created.') }
        format.xml  { render :xml => @student_group, :status => :created, :location => @student_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /student_groups/1
  # PUT /student_groups/1.xml
  def update
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      if @student_group.update_attributes(params[:student_group])
        format.html { redirect_to(@student_group, :notice => 'Student group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /student_groups/1
  # DELETE /student_groups/1.xml
  def destroy
    @student_group = StudentGroup.find(params[:id])
    @student_group.destroy

    respond_to do |format|
      format.html { redirect_to(student_groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/student_groups_helper.rb
# -*- encoding : utf-8 -*-
module StudentGroupsHelper
end

app/views/student_groups/_form.html.erb
<%= form_for(@student_group) do |f| %>
  <% if @student_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_group.errors.count, "error") %> prohibited this student_group from being saved:</h2>

      <ul>
      <% @student_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :studentclass_id %><br />
    <%= f.text_field :studentclass_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_groups/edit.html.erb
<h1>Editing student_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_group %> |
<%= link_to 'Back', student_groups_path %>

app/views/student_groups/index.html.erb
<h1>Listing student_groups</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Studentclass</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_groups.each do |student_group| %>
  <tr>
    <td><%= student_group.student_id %></td>
    <td><%= student_group.studentclass_id %></td>
    <td><%= link_to 'Show', student_group %></td>
    <td><%= link_to 'Edit', edit_student_group_path(student_group) %></td>
    <td><%= link_to 'Destroy', student_group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student group', new_student_group_path %>

app/views/student_groups/new.html.erb
<h1>New student_group</h1>

<%= render 'form' %>

<%= link_to 'Back', student_groups_path %>

app/views/student_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @student_group.student_id %>
</p>

<p>
  <b>Studentclass:</b>
  <%= @student_group.studentclass_id %>
</p>


<%= link_to 'Edit', edit_student_group_path(@student_group) %> |
<%= link_to 'Back', student_groups_path %>