config/routes.rb
DanceApp::Application.routes.draw do
  resources :subjects

  resources :student_groups

  resources :student_classes
  resources :class_students

  resources :teachers

  resources :lounges
  resources :teachers  
  resources :centers
  resources :users
  resources :sessions
  resources :students
  root  :to => 'sessions#new'
  match '/mainMenu', :to => 'pages#mainMenu'
  match '/userAdd', :to => 'users#new'
  match '/userClear', :to => 'users#clearUser' 
  match '/studentClear', :to => 'students#clearStudent'   
  match '/teacherClear', :to => 'teachers#clearTeacher'     
  match '/teacherAfterSubmit', :to => 'teachers#afterSubmit'       
  match '/centerClear', :to => 'centers#clear_center'     
  match '/subjectClear', :to => 'subjects#clear_subject'
  match '/loungeClear', :to => 'lounges#clear_lounge'       
  match '/StudentClassClear', :to => 'student_classes#clear_student_class'  
  match '/signout', :to => 'sessions#destroy'

end

app/controllers/student_classes_controller.rb
# -*- encoding : utf-8 -*-
class StudentClassesController < ApplicationController
before_filter :authenticate, :only=>[:index, :edit, :show, :new, :create, :destroy]          
  # GET /student_classes
  # GET /student_classes.xml
  #@default = "nonil"
  @hasError = 0
  def index
    @hasError = 0
    @student_class = StudentClass.new
    restore_lists
    getLounges
    createDayOfWeek
    0.upto @dayOfWeek.count-1 do|i|
    end
    
  end

  # GET /student_classes/1
  # GET /student_classes/1.xml
  def show
    @student_class = StudentClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student_class }
    end
  end

  # GET /student_classes/new
  # GET /student_classes/new.xml
  def new
    @student_class = StudentClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student_class }
    end
  end

  # GET /student_classes/1/edit
  def edit
    @student_class = StudentClass.find(params[:id])
    @student_class.student_class_dayweeks.each {|class_day|
        filling_dates(@student_class, class_day)
    }
    #@selected_center: variable used for lounge list selection
    @selected_center = @student_class.lounge_id
    @selected_subject = @student_class.subject_id
    restore_lists
    createDayOfWeek
  end

  # POST /student_classes
  # POST /student_classes.xml
  def create
    hasError = 0
    createDayOfWeek
    @centers = Center.all
    @student_class = StudentClass.new(params[:student_class])
    @all_students = Student.all
    @all_teachers = Teacher.all
    @default ="S"
    if @student_class.Mon_check == "0" and @student_class.Tue_check == "0" and
       @student_class.Wed_check == "0" and @student_class.Thu_check == "0" and
       @student_class.Fri_check == "0" and @student_class.Sat_check == "0" and
       @student_class.Sun_check == "0"
      session[:error] ="You have to choose one day of week at least."
      hasError = 1
    end
    #######################################################
    #########Adding hours and minutes from date fields#####
    #######################################################
    adding_hours
    getLounges
    #######################################################
    ###########Adding students from checked ones###########
    #######################################################    
    adding_students
    #######################################################
    ###########Adding teachers from checked ones###########
    #######################################################   
    hasError == 0
    adding_teachers
    if hasError == 0
        if @student_class.save and 
            @student_class = StudentClass.new
        end
    end
    @all_student_classes = StudentClass.all  
  end

  # PUT /student_classes/1
  # PUT /student_classes/1.xml
  def update
    #we're getting the current form field's values
    @student_class = StudentClass.new(params[:student_class])    
    hasError = 0
    if @student_class.Mon_check == "0" and @student_class.Tue_check == "0" and
       @student_class.Wed_check == "0" and @student_class.Thu_check == "0" and
       @student_class.Fri_check == "0" and @student_class.Sat_check == "0" and
       @student_class.Sun_check == "0"
      session[:error] ="You have to choose one day of week at least."
      hasError = 1
    end
    if hasError == 0
        @student_class = StudentClass.find(params[:id])      
        

        #if @student_class.save
        if @student_class.update_attributes(params[:student_class])
          @student_class.student_class_dayweeks.delete_all
          adding_hours      
          @student_class.student_class_students.delete_all    
          adding_students      
          @student_class.student_class_teachers.delete_all
          adding_teachers      
          @student_class = StudentClass.new
        end
     end
     restore_lists
     createDayOfWeek
  end

  # DELETE /student_classes/1
  # DELETE /student_classes/1.xml
  def destroy
    @student_class = StudentClass.find(params[:id])
    @student_class.destroy
    restore_lists
    createDayOfWeek
    @student_class = StudentClass.new

  #  respond_to do |format|
  #    format.html { redirect_to(student_classes_url) }
  #    format.xml  { head :ok }
  #  end
  end
  def getLounges
    @lounges_by_center = Lounge.all    
  end
  def createDayOfWeek
    @dayOfWeek = Dayweek.all
  end
  def add_minutes_hour fromh, fromm, toh, tom, dayweek
      student_class_dayweek = StudentClassDayweek.new
      student_class_dayweek.from_time = fromh
      student_class_dayweek.from_time = student_class_dayweek.from_time + fromm      
      student_class_dayweek.to_time = toh
      student_class_dayweek.to_time = student_class_dayweek.to_time + tom   
      student_class_dayweek.dayweek = dayweek
      return student_class_dayweek
  end 
  #########################################################################################
  ###########remove left/right spaces and pad left side with 0 if it's necesary############
  #########################################################################################
  def format_hour_minute(hour_minute)
    hour_minute.lstrip.rstrip.rjust(2,'0')    
  end
  #########################################################################################
  ################################restore all page's lists#################################
  #########################################################################################  
  def restore_lists
    @all_student_classes = StudentClass.all 
    @all_students = Student.all
    @all_teachers = Teacher.all    
  end
  #########################################################################################
  ###########################fill time and day of the week#################################
  #########################################################################################    
  def filling_dates (student_class, class_day)
        prefix = Dayweek.find_by_id(class_day.dayweek_id).dayname
        if prefix == "Monday"
            student_class.Mon_fromh = class_day.from_time[0,2]
            student_class.Mon_fromm = class_day.from_time[2,2]
            student_class.Mon_toh = class_day.to_time[0,2]
            student_class.Mon_tom = class_day.to_time[2,2]                      
            student_class.Mon_check = "1"
        end
        if prefix == "Tuesday"
            student_class.Tue_fromh = class_day.from_time[0,2]
            student_class.Tue_fromm = class_day.from_time[2,2]
            student_class.Tue_toh = class_day.to_time[0,2]
            student_class.Tue_tom = class_day.to_time[2,2]
            student_class.Tue_check = "1"
        end
        
        if prefix == "Wednesday"
            student_class.Wed_check = "1"
            student_class.Wed_fromh = class_day.from_time[0,2]
            student_class.Wed_fromm = class_day.from_time[2,2]
            student_class.Wed_toh = class_day.to_time[0,2]
            student_class.Wed_tom = class_day.to_time[2,2]
            student_class.Wed_check = "1"            
        end
        if prefix == "Thursday"
            student_class.Thu_fromh = class_day.from_time[0,2]
            student_class.Thu_fromm = class_day.from_time[2,2]
            student_class.Thu_toh = class_day.to_time[0,2]
            student_class.Thu_tom = class_day.to_time[2,2]
            student_class.Thu_check = "1"
        end
        if prefix == "Friday"
            student_class.Fri_fromh = class_day.from_time[0,2]
            student_class.Fri_fromm = class_day.from_time[2,2]
            student_class.Fri_toh = class_day.to_time[0,2]
            student_class.Fri_tom = class_day.to_time[2,2]            
            student_class.Fri_check = "1"            
        end
        if prefix == "Saturday"
            student_class.Sat_fromh = class_day.from_time[0,2]
            student_class.Sat_fromm = class_day.from_time[2,2]
            student_class.Sat_toh = class_day.to_time[0,2]
            student_class.Sat_tom = class_day.to_time[2,2]            
            student_class.Sat_check = "1"             
        end
        if prefix == "Sunday"    
            student_class.Sun_fromh = class_day.from_time[0,2]
            student_class.Sun_fromm = class_day.from_time[2,2]
            student_class.Sun_toh = class_day.to_time[0,2]
            student_class.Sun_tom = class_day.to_time[2,2]
            student_class.Sun_check = "1"
        end
  end
  def clear_student_class
    redirect_to student_classes_path
  end
  #######################################################
  #########Adding hours and minutes from date fields#####
  #######################################################  
  def adding_hours
    if @student_class.Mon_check == "1"
      @student_class_dayweek = add_minutes_hour format_hour_minute(@student_class.Mon_fromh), format_hour_minute(@student_class.Mon_fromm), format_hour_minute(@student_class.Mon_toh), format_hour_minute(@student_class.Mon_tom), Dayweek.find_by_abbreviation("Mon")
      @student_class.student_class_dayweeks << @student_class_dayweek
    end
    if @student_class.Tue_check == "1"
      @student_class_dayweek = add_minutes_hour format_hour_minute(@student_class.Tue_fromh), format_hour_minute(@student_class.Tue_fromm), format_hour_minute(@student_class.Tue_toh), format_hour_minute(@student_class.Tue_tom), Dayweek.find_by_abbreviation("Tue")
      @student_class.student_class_dayweeks << @student_class_dayweek
    end
    if @student_class.Wed_check == "1"
      @student_class_dayweek = add_minutes_hour format_hour_minute(@student_class.Wed_fromh), format_hour_minute(@student_class.Wed_fromm), format_hour_minute(@student_class.Wed_toh), format_hour_minute(@student_class.Wed_tom), Dayweek.find_by_abbreviation("Wed")
      @student_class.student_class_dayweeks << @student_class_dayweek
    end  
    if @student_class.Thu_check == "1"

app/helpers/student_classes_helper.rb
# -*- encoding : utf-8 -*-
module StudentClassesHelper
    cont_row = 1
    def student_list_selection (student_id)
    ret = false
    @student_class.student_class_students.each {|student|      
      if student_id == student.student_id
        ret = true
        break
      end
    }
    return ret
  end
  def teacher_list_selection_student_class (teacher_id)
    ret = false
    @student_class.student_class_teachers.each {|teacher|      
      if teacher_id == teacher.teacher_id
        ret = true
        break
      end
    }
    return ret
  end  
end
def table_teachers
  collection_rows = Array.new
  collection_headers = Array.new    
  header = Array.new
  @all_student_classes.each {|student_class|
    column_values = Array.new
    column_values << student_class.name
    column_values << student_class.description
    column_values << student_class.lounge.name
    column_values << student_class.lounge.center.name
    column_values << String(student_class.id)
    collection_rows << column_values
  }
  header << "Name"
  header << "Surname1"
  header << "Surname2"
  header << "Action"
  making_table(collection_rows, header, 4, "teachers")  
end
def table_classes
  
  collection_rows = Array.new
  collection_headers = Array.new    
  header = Array.new
  @all_student_classes.each {|student_class|
    column_values = Array.new
    column_values << student_class.subject.name
    column_values << student_class.description
    column_values << student_class.lounge.name
    column_values << student_class.lounge.center.name
    column_values << String(student_class.id)
    collection_rows << column_values
  }
  header << "Name"
  header << "Description"
  header << "Lounge"
  header << "Center"
  header << "Action"
  making_table(collection_rows, header, 4, "student_classes")
end

app/views/student_classes/_form.html.erb
<%= form_for(@student_class) do |f| %>
  <div class="centered_errors">
    <%= render 'shared/error_message', :object => f.object  %>
  </div>
<div class="centered_student_classes">
  <table border ="0">    
    <tr>
      <td><%=f.label :subject%></td>
      <td><%=collection_select(:student_class, :subject_id, Subject.all, :id, :name, { :selected => @selected_subject })%></td>        

      <td width="155"></td>      
      <td><%=f.label :description%></td>
      <td><%=f.text_field(:description)%></td>      
    </tr>
    <tr>
      <td><%= f.label :lounge %></td>
      <td><%=f.select :lounge_id, option_groups_from_collection_for_select(Center.all, :lounges, :name, :id, :name, @selected_center)%></td>
    </tr>        
  </table>
  <div style="position: absolute; left: 350px; top: 106px" id="days_of_week">
          <table border="0">
            <%@dayOfWeek.each do |dayOfWeek|%>
              <tr>
                <td><%=f.label dayOfWeek.abbreviation%></td>
                <td><%=f.check_box dayOfWeek.abbreviation+"_check"%></td>         
                <td><%=f.label "Start time"%></td>
                <% if @student_class.errors[dayOfWeek.abbreviation+"_fromh"].any?%> 
                    <td><%=f.text_field dayOfWeek.abbreviation+"_fromh", :class => "error_date_time", :maxlength=>"2"%></td>            
                <%else%>
                    <td><%=f.text_field dayOfWeek.abbreviation+"_fromh", :class => "date_time",  :maxlength=>"2"%></td>                
                <%end%>
                <td>:</td>          
                <% if @student_class.errors[dayOfWeek.abbreviation+"_fromm"].any?%>  
                    <td><%=f.text_field dayOfWeek.abbreviation+"_fromm", :class => "error_date_time", :maxlength=>"2"%></td>          
                <%else%>
                    <td><%=f.text_field dayOfWeek.abbreviation+"_fromm", :class => "date_time", :maxlength=>"2"%></td>
                <%end%>
                <td>_________</td>
                <td><%=f.label "End time"%></td>   
                <% if @student_class.errors[dayOfWeek.abbreviation+"_toh"].any?%>           
                     <td><%=f.text_field dayOfWeek.abbreviation+"_toh", :class => "error_date_time", :maxlength=>"2"%></td>
                <%else%>
                     <td><%=f.text_field dayOfWeek.abbreviation+"_toh", :class => "date_time", :maxlength=>"2"%></td>
                <%end%>
                <td>:</td>  
                <% if @student_class.errors[dayOfWeek.abbreviation+"_tom"].any?%>
                  <td><%=f.text_field dayOfWeek.abbreviation+"_tom", :class => "error_date_time", :maxlength=>"2"%></td>
                <%else%>
                  <td><%=f.text_field dayOfWeek.abbreviation+"_tom", :class => "date_time", :maxlength=>"2"%></td>          
              <%end%>
              </tr>
            <%end%>
          </table>   
  </div>
        <div style="position: absolute; top: 110px; left: 800px;" id="div_student">
          <table width="292" >
            <tr align="center">
              <td>STUDENTS</td>
            </tr>
          </table>
          <div style="overflow: scroll; border: black 1px solid; height: 550px;">
            <table width="292" class="altrowstable">
            <tr class="headercolor">
                <td align ="Center">Name</td>
                <td align ="Center">Surname1</td>
                <td align ="Center">Surname2</td>
                <td align ="Center">Selector</td>              
            </tr>                                            
              <%cont_row=1
              @all_students.each do |student| %>
                  <%if cont_row%2==0%>
                    <tr class="oddrowcolor">
                  <%else%>
                    <tr class="evenrowcolor">                    
                  <%end
                    cont_row = cont_row+1%>
                        <td><%=f.label student.name%></td>
                        <td><%=f.label student.surname1%></td>    
                        <td><%=f.label student.surname2%></td>
                      
                        <%if student_list_selection(student.id) == true%>
                            <td align="Center"><%=check_box_tag 'students_id[]', student.id, true%></td>
                        <%else%>
                            <td align="Center"><%=check_box_tag 'students_id[]', student.id, false%></td>
                        <%end%>
                    </tr>
                <% end %>
            </table> 
          </div>
        </div>
        <div style="position: absolute; top: 110px; left: 0%;" id="div_teacher">        
          <table  width="292">
            <tr align="center">
              <td>TEACHERS</td>
            </tr>
          </table>
          <div style="overflow: scroll; border: black 1px solid; height: 550px;">
               <table width="292" class="altrowstable">  
                  <tr class="headercolor">
                    <td align ="Center">Name</td>
                    <td align ="Center">Surname1</td>
                    <td align ="Center">Surname2</td>
                    <td align ="Center">Selector</td>              
                  </tr>                                
                  <%cont_row=1
                  @all_teachers.each do |teacher| %>
                  <%if cont_row%2==0%>
                      <tr class="oddrowcolor">
                  <%else%>
                      <tr class="evenrowcolor">
                  <%end
                    cont_row = cont_row+1%>
                    <td><%=f.label teacher.name%></td>
                    <td><%=f.label teacher.surname1%></td>
                    <td><%=f.label teacher.surname2%></td>              
                    <%if teacher_list_selection_student_class(teacher.id) == true%>
                        <td align="Center"><%=check_box_tag 'teachers_id[]', teacher.id, true%></td>
                    <%else%>
                        <td align="Center"><%=check_box_tag 'teachers_id[]', teacher.id, false%></td>
                    <%end%>
                  </tr>    
                <%end%>
             </table>
          </div>
        </div>             

  <div style="position:absolute; left: 320px; top: 310px; "id="div_classes">
          <table>
              <tr align="center"><td>CLASSES</td></tr>      
              <tr style="top: 0%;"><td><%=table_classes%></td></tr>
          </table>            
  </div>
<!--  <input name="Fade" value ="Show teacher" type="button" onclick="fade_element('div_teacher');"/>
  <input name="Fade" value ="Show student" type="button" onclick="fade_element('div_student');"/>  
  <div style="position: relative; padding-top: 10px; left: 15%"> -->
<!----------------------------------------------------------->
  <div style="position: absolute; padding-top: 10px">
      <%= f.submit %>
      <input name="Clear" value ="Clear" type="button" onclick="location.href='/StudentClassClear'"/>    
      <input name="MainMenu" value ="Main menu" type="button" onclick="location.href='/mainMenu'"/>
  </div>
  </div>
  <% if session[:error] != nil %>
      <script>alert("<%=session[:error]%>")</script>
      <%session[:error] = nil%>
  <% end %>

<%end%>
</div>

app/views/student_classes/create.html.erb
<%=render 'form' %>

app/views/student_classes/destroy.html.erb
<%=render 'form' %>

app/views/student_classes/edit.html.erb
<%=render 'form' %>

app/views/student_classes/index.html.erb
<%=render 'form' %>

app/views/student_classes/new.html.erb
<h1>New student_class</h1>

<%= render 'form' %>

<%= link_to 'Back', student_classes_path %>

app/views/student_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lounge:</b>
  <%= @student_class.lounge_id %>
</p>

<p>
  <b>Teacher:</b>
  <%= @student_class.teacher_id %>
</p>

<p>
  <b>Studentgroup:</b>
  <%= @student_class.studentgroup_id %>
</p>


<%= link_to 'Edit', edit_student_class_path(@student_class) %> |
<%= link_to 'Back', student_classes_path %>

app/views/student_classes/update.html.erb
<%= render 'form' %>